### ISSUE TITLE
User has CSS issues.

### ISSUE THREAD

**Issue by paulbearddotname** [openlcb/uniqueidregistry#2]
Via Alex, the user reports that:
- They are using dialup.
- They are using a slightly older version of Firefox.
- Some of the input fields overlapped part of the re-captcha.

**Comment by paulbearddotname** [comment]
To reproduce this issue we need:
- The version of Firefox the user was using.
- It may be helpful to know the operating system the user was using.

**Comment by paulbearddotname** [comment]
The current version of Firefox is version 44.

**Comment by paulbearddotname** [comment]
The Apache server access log shows a request for a Unique ID Range was made around the same time using Firefox 38 on Linux.

**Comment by paulbearddotname** [comment]
The site looks fine in Firefox 44.

**Comment by paulbearddotname** [comment]
The site looks fine in Firefox 38 on Mac OS X.

**Comment by paulbearddotname** [comment]
Reproduced by removing reCAPTCHA stylesheet.
I suspect that since the user was using dial-up, the stylesheet was still loading.
There is nothing to fix.

**Comment by dpharris** [comment]
Good sleuthing, thanks!

David
